// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeTg4h9XSZ3SumsisrGblWEwcCS3LSvKA',
    appId: '1:509668840507:web:524f0fb3ed6c6c264db81e',
    messagingSenderId: '509668840507',
    projectId: 'globalchat-da657',
    authDomain: 'globalchat-da657.firebaseapp.com',
    storageBucket: 'globalchat-da657.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwMHprTiPrLVp4a6qeyTjeralMVRjQ0j8',
    appId: '1:509668840507:android:546f7f9b99146a5a4db81e',
    messagingSenderId: '509668840507',
    projectId: 'globalchat-da657',
    storageBucket: 'globalchat-da657.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqtUN0XXk0m793V7_aaaRE432ON_PuztE',
    appId: '1:509668840507:ios:dfa20b41b877c5824db81e',
    messagingSenderId: '509668840507',
    projectId: 'globalchat-da657',
    storageBucket: 'globalchat-da657.firebasestorage.app',
    iosBundleId: 'com.dummyapps.globalchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqtUN0XXk0m793V7_aaaRE432ON_PuztE',
    appId: '1:509668840507:ios:dfa20b41b877c5824db81e',
    messagingSenderId: '509668840507',
    projectId: 'globalchat-da657',
    storageBucket: 'globalchat-da657.firebasestorage.app',
    iosBundleId: 'com.dummyapps.globalchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeTg4h9XSZ3SumsisrGblWEwcCS3LSvKA',
    appId: '1:509668840507:web:c96fd575012201264db81e',
    messagingSenderId: '509668840507',
    projectId: 'globalchat-da657',
    authDomain: 'globalchat-da657.firebaseapp.com',
    storageBucket: 'globalchat-da657.firebasestorage.app',
  );
}
